### ISSUE TITLE
3rd Node MCU code

### ISSUE THREAD

**Issue by NBvinay** [NBvinay/Automatic-Railway-Crossing-IOT-#1]
add third node mcu program to repo.

**Comment by sgagankumar** [comment]
Done boss, the third NodeMCU program has been added to the repository. Please check Train_3.ino file for the code. 
Its compiled and tested for no error.
If the code doesn't compile there might be a error with your installed libraries, please use the following download link for fulling working LCD arduino I2C Libraries - https://github.com/sgagankumar/LiquidCrystal_I2C_ArduinoLibrary
